### ISSUE TITLE
Get access token

### ISSUE THREAD

**Issue by PavelBaykov** [Azure-Samples/active-directory-b2c-dotnetcore-webapp#13]
Hi, thanks for example - thats the only example of ASP Core and Azure B2C in the world)

While using MVC5 and OWIN there was an opportunity to get Access token using ClaimsPrincipal.Current.
Articles: [1](https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-devquickstarts-api-dotnet), [2](http://bitoftech.net/2016/08/31/integrate-azure-ad-b2c-asp-net-mvc-web-app/)

According to this article, [2](http://bitoftech.net/2016/08/31/integrate-azure-ad-b2c-asp-net-mvc-web-app/), we could 

> SaveSigninToken = true //important to save the token in boostrapcontext

and get access token

>ClaimsPrincipal.Current.Identities.First().BootstrapContext as System.IdentityModel.Tokens.BootstrapContext;) 

to use in in requests to some WebApis from MVC application.

Unfortunately, in your app (I use Core 1.0.1 version) ClaimsPrincipal.Current is **null**.

I know I can make a POST request using ClientSecret([3](https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-reference-oidc)) to get AccessToken, but I am pretty sure this approach is wrong. 

What is the correct way to get acces token from B2C in Core application so I could pass it as a bearer to some other web apis?

**Comment by gsacavdm** [comment]
We'll update this sample in the next few weeks to do access tokens properly which involves a very different approach. This approach involves **using access tokens rather than the id_token** (no more SaveSigninToken and Bootstrap context). To do this you'll need:
1. Register your web api and define scopes for it 
2. In your web app's registration, indicate that you want to consume those scopes. 
3. Change your web app's OpenID Connect middle ware:
   1. **Response type** of "id_token **code**"
   2. **Scope** of "openid **{your-web-api-scopes}**"
4. Finally, you'll **use MSAL in the OnTokenResponseReceived** event to redeem the code for an access token.

**Comment by gsacavdm** [comment]
See #16

**Comment by gsacavdm** [comment]
The sample has been updated with support for access tokens (readme update pending though).
