### ISSUE TITLE
Having Trouble Reproducing Demo

### ISSUE THREAD

**Issue by ghost** [Azure-Samples/active-directory-b2c-dotnetcore-webapp#46]
I've followed the steps as best I could but I'm having trouble with Step #4.  I'm afraid my node.js just isn't good enough to translate.  Is there an MVC version of the protected API somewhere?
It'd be real handy if there was a .net core version of the API part of this demo in the repository.

**Comment by skorpionet100** [comment]
same here, I click the Sign In link, code runs, but no effect at all.... Razor with Azure B2C is a pain because also the VS 2017 web app core with Azure B2C authentication template isn't working due an Exception "Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ValidateAntiforgeryTokenAuthorizationFilter:Information: Antiforgery token validation failed. The required antiforgery cookie ".AspNetCore.Antiforgery.tzYDuZ2Kg7I" is not present.

Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The required antiforgery cookie ".AspNetCore.Antiforgery.tzYDuZ2Kg7I" is not present."

**Comment by parakhj** [comment]
@Dark-Bond there is a .net core version of the sample for api's here: https://github.com/Azure-Samples/active-directory-b2c-dotnetcore-webapi

**Comment by Dark-Bond** [comment]
Thanks.  This version seems to work pretty well.

**Comment by jmprieur** [comment]
Closing this issue as this sample is being archived and replaced by a newer ASP.NET Core 3.1 sample.
See Readme.md
