### ISSUE TITLE
Infinite redirection in IE and Edge

### ISSUE THREAD

**Issue by krunal039** [Azure-Samples/active-directory-b2c-dotnetcore-webapp#9]
We have used azure b2c with customize Azure AD B2C user interface page and when user try to loging with IE/Edge it stuck between redirection azure website and https://login.microsoftonline.com and keep redirecting users in between. two sites

**Comment by gsacavdm** [comment]
Is this an issue you are experiencing when running this particular sample as is or an issue you're experiencing with your own implementation or a modified version of this sample.

If the former, please provide more details so that we can assist.
If the latter, you should create a post (with more details too) in [StackOverflow with the tag azure-ad-b2c] (http://stackoverflow.com/questions/tagged/azure-ad-b2c)
